platform :ios, '12.0'
target 'MyRealmProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for MyRealmProject
  pod 'Realm', '=10.0.0-beta.2'
end

